---
- name: provision RPi as Torrent Box
  hosts: all
  vars:
    pia_location: 'CA Toronto'
    iptables: true
    packages:
      - openvpn
      - deluged
      - deluge-console
      - samba
      - samba-common-bin
      - minidlna
      - iptables-persistent
      - ntfs-3g
      - exfat-fuse
      - nftables

  vars_files:
    - vars/static_ips.yml
    - vars/pia_credentials.yml
    - vars/deluge.yml
    - vars/samba.yml
    - vars/usb_ids.yml

  vars_prompt:
    - name: pia_username
      prompt: 'please enter your Private Internet Access account username:'
      private: no
    - name: pia_password
      prompt: 'please enter your Private Internet Access account password:'
      private: yes
    - name: rssfeed_url
      prompt: 'please enter your ShowRSS Personal RSS Feed URL:'
      private: no
    - name: usb_vendor_id
      prompt: 'please enter your USB Device Vendor ID:'
      private: no
    - name: usb_model_id
      prompt: 'please enter your USB Device Model ID:'
      private: no

  remote_user: pi
  become_method: sudo

  tasks:
    - import_tasks: ./tasks/update.yml
      tags: update

    - import_tasks: ./tasks/vnc.yml
      tags: vnc

    - import_tasks: ./tasks/static_ip.yml
      tags: static_ip

    - import_tasks: ./tasks/packages.yml
      tags: packages

    - import_tasks: ./tasks/pia.yml
      tags: pia

    - import_tasks: ./tasks/deluge.yml
      tags: deluge

    - import_tasks: ./tasks/samba.yml
      tags: samba

    - import_tasks: ./tasks/minidlna.yml
      tags: minidlna

    - import_tasks: ./tasks/usb_poweroff.yml
      tags: usb_poweroff

    - import_tasks: ./tasks/iptables.yml
      tags: iptables
      when: iptables

    - import_tasks: ./tasks/nftables.yml
      tags: nftables
      when: not iptables

    - import_tasks: ./tasks/reboot.yml
      tags: reboot
